Update changes

diff --git a/01-mongodb b/01-mongodb
--- a/01-mongodb
+++ b/01-mongodb
@@ -27,9 +27,14 @@ fi
 
 VALIDATE (){
     if [ $1 -ne o ]; then
-     echo -e "$TIMESTAMP [ERROR] $2 ... $G FIALURE... $N" | tee -a $LOGS_FILE
+     echo -e "$TIMESTAMP [ERROR] $2 ... $R FIALURE... $N" | tee -a $LOGS_FILE
        exit 1
     else
-       echo -e "INFORM IT  when $2...$R SUCCESS $Y" | tee -a $LOGS_FILE
+       echo -e "INFORM IT  when $2...$G SUCCESS $Y" | tee -a $LOGS_FILE
      fi  
 }
+
+
+cp mongo.repo /etc/yum.repos.d/mongo.repo
+  VALIDATE $? "Adding mongo repo"
+  
